Percentage: true

VotesNeeded:
  ban: 50
  kick: 50
  tempban: 50
  
VoteLimits: true
MaxVotes:
    ban: 15
    kick: 15
    tempban: 15
    
UseTimer: true
Delay:
  Ban: 60
  Kick: 60
  Tempban: 60

UseMaxtime: true
MaxTimeTempBan: 120

